#!/bin/bash

j=1
while [ $j -le 20 ]; do
echo -n "$j "
gnuplot -persist<< EOF
reset

#set terminal postscript eps enhanced size 8.5cm,6cm color font "Times,20" linewidth 10
set terminal png large size 1600,720 enhanced

set pm3d map

set xlabel "x" 
set ylabel "y"


#set xtics 5
#set ytics 1
set palette defined (0 0 0 0, 1 0 0 1, 3 0 1 0, 4 1 0 0, 6 1 1 1)

jj=${j}

#set cbrange[-1:1]
set xrange[:]
set yrange[:]

set output 'frame'.jj.'.png'
splot for [i=0:2:1] 'r'.i.'E_time'.jj.'.dat' u 1:2:3 w pm3d notitle
#splot 'r0E_time'.jj.'.dat' u 1:2:3 w pm3d notitle

EOF

    let j=j+1
done
echo ""

