#!/bin/bash



gnuplot -persist<< EOF
reset

#set terminal postscript eps enhanced size 8.5cm,6cm color font "Times,20" linewidth 10
#set term png
#set output "frame$1.png"
set pm3d map

set xlabel "x" 
set ylabel "y"

#set xtics 5
#set ytics 1
set palette defined (0 0 0 0, 1 0 0 1, 3 0 1 0, 4 1 0 0, 6 1 1 1)

jj=$1

#set cbrange[-1:1]
set title "frame=$1"

#splot for [i=0:1:1]'r'.i.'Ekc_time'.jj.'.dat' u 1:2:3 w pm3d notitle
splot 'r0Ekc_time'.jj.'.dat' u 1:2:3 w pm3d notitle

EOF

