#!/bin/bash
#sh clear.sh 40
#check="-fcheck=all"

FC=mpifort
dest="../../obj/misc/"
srcFiles=($(ls *.f90))

############################
#outputDirective for mpifort(intel)
############################
#OD="-module"
############################
#outputDirective for mpifort(GNU)
############################
OD="-J"
############################

for srcfile in "${srcFiles[@]}" ;do
#    $FC $check -c $srcfile $OD $dest 
    $FC $check $OD $dest -o $dest${srcfile%.*}.o  -c $srcfile
#    echo "-c $srcfile"
done

#mpifort $check -J${obj} -c $src/constants_mod.f90 -o $obj/constants_mod.o
#mpifort $check -J${obj} -c $src/mydatatypes.f90 -o $obj/mydatatypes.o
#mpifort $check -J${obj} -c $src/findroots_mod.f90 -o $obj/findroots_mod.o
#mpifort $check -J${obj} -c $src/my_matfunctions_mod.f90 -o $obj/my_matfunctions_mod.o


