#!/bin/bash

j=1
while [ $j -le 20 ]; do
echo -n "$j "
gnuplot -persist<< EOF
reset

#set terminal postscript eps enhanced size 8.5cm,6cm color font "Times,20" linewidth 10
set terminal png large size 1600,720 enhanced

jj=${j}
set output 'fld'.jj.'.png'
set multiplot layout 2,1
set xlabel "y(nm)" 


#set xtics 5
#set ytics 1

set title "Air-PML inteface, ds=4nm, npml=10,R(0)=exp(-16)"

#set yrange[-1:1]
#set xrange[:500]
set g
set mytics 2

#set xtics add('i' 380,'f' 12343)
#set xtics add('i' 1582,'f' 11077)

set style line 100 lt 1 lc rgb "gray" lw 3
set style line 101 lt 1 lc rgb "gray" lw 2
set grid xtics ytics ls 100
set grid mxtics mytics ls 101

#set xtics add('s' 37,'SiO' 80,'Si' 85,'' 105,'' 125)
#plot for [i=0:3:1] 'r'.i.'E_time'.jj.'.dat' u 1:2 w l lt 1 lw 3 title ""

set ylabel "Ex"
plot for[i=0:2]'r'.i.'E_time'.jj.'.dat' u 1:2 w l lt 1 lw 3 notitle

set ylabel "Hz"
plot for[i=0:2]'r'.i.'E_time'.jj.'.dat' u 1:3 w l lt 2 lw 3 notitle

EOF

    let j=j+1
done
echo ""

