#!/bin/bash

gnuplot -persist<< EOF
reset

#set terminal postscript eps enhanced size 8.5cm,6cm color font "Times,20" linewidth 10
#set terminal png large size 1600,720 enhanced

set xlabel "wavelength(nm)" 
set ylabel "pos. x(nm)" 

#set title "3D real[Ex]real[Hz]"
amp=1.e-30
set title "3D img[Ex]img[Hz]"
#set pm3d map


set view 90,360
splot [:][:][:]\\
"r0tf_r.dat" u 1:2:(\$6/amp) w pm3d notitle


EOF

